WIP: Sync Refactoring
bzbd/zenfs pull request #34
Opened 2021-09-13 07:06 UTC by levisonchen

Initial commit : 
Add state enumeration and structure declaration.

2021-09-13 09:37 UTC, royguo commented on fs/zbd_zenfs.h
> +enum ZoneState {
1. We should document this `ZoneState` to help users better understand the underlying state-changing mechanism.
2. I would prefer to create a separate `MetaZoneState` to clarify this

2021-09-13 21:02 UTC, weilewei reviewed
Adding some minor comments.

2021-09-13 21:02 UTC, weilewei commented on fs/zbd_zenfs.h
> +enum ZoneState { kEmpty = 0, kActive, kReadOnly, kMetaLog, kMetaSnapshot };
just curious, why every state variable starts with k? like kEmpty, kActive? is it something convectional thing?

2021-09-13 21:02 UTC, weilewei commented on fs/zbd_zenfs.h
> +  virtual void operator()() { fn_(arg_); }
Would it be more explicit to use a member function like `void run()` instead of `operator` when we intend to run a background job? A verb makes code more readable. So in user code, we can see

```
BackgroundJob job(...);
job.run();
```
However, when reviewing code `(*job_now_)();` above in `fs/zbd_zenfs.cc`, I need to refer back to operator definition and see what does this operator mean.

Or is there any advantage here using operator that I am not aware of?

2021-09-13 21:02 UTC, weilewei commented on fs/zbd_zenfs.cc
> +BackgroundWorker::BackgroundWorker(bool run_at_beginning) {
I wonder why do we need run_at_beginning here? Will someone start background worker in the middle of a running program?

2021-09-14 01:56 UTC, levisonchen commented on fs/zbd_zenfs.h
> +enum ZoneState { kEmpty = 0, kActive, kReadOnly, kMetaLog, kMetaSnapshot };
It's a conventional code style for enumeration.

2021-09-14 02:01 UTC, levisonchen commented on fs/zbd_zenfs.h
> +  virtual void operator()() { fn_(arg_); }
Actually, this operator "()" stands for "run" in c++, just like "+" stands for "add"...
Besides that, you don't have to call "run" manually, just submit a job to worker, the bg worker will do that.

2021-09-14 02:26 UTC, royguo commented on fs/zbd_zenfs.cc
> +BackgroundWorker::BackgroundWorker(bool run_at_beginning) {
Agree, though it doesn't hurt anyone, If we don't have a strong reason to add this parameter, the first principle is not to add it.

2021-09-14 02:29 UTC, levisonchen commented on fs/zbd_zenfs.cc
> +BackgroundWorker::BackgroundWorker(bool run_at_beginning) {
For debug, with this I could start the worker without runing immediately, then I could submit a job, running the worker, pause, and etc...

2021-09-14 03:00 UTC, weilewei commented on fs/zbd_zenfs.cc
> +BackgroundWorker::BackgroundWorker(bool run_at_beginning) {
can we add a comment say `TODO: adding run_at_beginning for debugging purpose, will remove later`

2021-09-14 03:07 UTC, royguo requested changes

2021-09-14 03:07 UTC, royguo commented on fs/zbd_zenfs.cc
> +void BackgroundWorker::Wait() {
To make things simpler, I suggest we remove all states in BackgroundWorker and make it automatically running on program startup.

2021-09-14 03:07 UTC, royguo commented on fs/zbd_zenfs.cc
> +void BackgroundWorker::SubmitJob(std::function<int(void*)> fn, void* arg) {
Is `SubmitJob` called from foreground threads? (e.g. A metadata rolling thread), if so we should avoid heavy locking here. Sometimes we use double task queue & try_lock to handle such cases:

task queue 1: [a,b,c,d,e,f] <--- worker locked
task queue 2: [g,v,g,z]      <--- SubmitJob locked

2021-09-14 03:07 UTC, royguo commented on fs/zbd_zenfs.h
> +  virtual void operator()() { fn_(arg_); }
If BackgroundJob is inherited from `std::thread` or `std::function`, the `()` makes sense, but here `BackgroundJob` belongs to none of these cases, so I agree with @weilewei we should explicitly use `run()` or `start()` to make things clear. (Weak suggestion, feel free to keep it if you insist).

2021-09-14 03:44 UTC, royguo approved these changes

2021-09-14 03:49 UTC, weilewei commented on fs/zbd_zenfs.h
> +  virtual ~BackgroundJob();
virtual ~BackgroundJob() {};

adding a `{}` makes compiler happy

2021-09-14 03:55 UTC, levisonchen commented on fs/zbd_zenfs.h
> +  virtual ~BackgroundJob();
Solved.

2021-09-14 04:04 UTC, levisonchen commented
This PR contains basic modules for sync refactoring, such as status and background worker.

2021-09-14 04:07 UTC, merged

2021-09-14 08:08 UTC, levisonchen commented on fs/zbd_zenfs.cc
> +BackgroundWorker::BackgroundWorker(bool run_at_beginning) {
Sure do.